# 模型配置
models:
  # 快速测试模型（7B参数，下载快）
  mistral-7b:
    model_name: "microsoft/DialoGPT-medium"  # 使用更稳定的测试模型
    max_length: 1024
    temperature: 0.1
    top_p: 0.9
    do_sample: true
    num_beams: 1
    
  longalpaca-7b:
    model_name: "Yukang/LongAlpaca-7B-16k"
    max_length: 2048
    temperature: 0.1
    top_p: 0.9
    do_sample: true
    num_beams: 1
    
  # 注释掉大模型（下载时间长，稍后使用）
  # llama-7b:
  #   model_name: "mistral-community/Mistral-7B-v0.2"
  #   max_length: 4096
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1
    
  # llama-13b:
  #   model_name: "Yukang/LongAlpaca-13B-16k"
  #   max_length: 8192
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1
    
  # llama-70b:
  #   model_name: "Yukang/LongAlpaca-70B-16k"
  #   max_length: 8192
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1
    
  # longalpaca-13b:
  #   model_name: "Yukang/LongAlpaca-13B-16k"
  #   max_length: 8192
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1
    
  # longalpaca-70b:
  #   model_name: "Yukang/LongAlpaca-70B-16k"
  #   max_length: 8192
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1
    
  # oasst-30b:
  #   model_name: "Yhyu13/oasst-rlhf-2-llama-30b-7k-steps-hf"
  #   max_length: 4096
  #   temperature: 0.1
  #   top_p: 0.9
  #   do_sample: true
  #   num_beams: 1

# 量化配置
quantization:
  4bit:
    load_in_4bit: true
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    
  8bit:
    load_in_8bit: true
    
  none:
    load_in_4bit: false
    load_in_8bit: false

# 数据集配置
datasets:
  # 高中数学数据集（推荐用于大模型测试）
  math:
    name: "hendrycks/math"
    split: "test"
    max_samples: 500  # 减少样本数，加快测试
    prompt_template: "Solve the following math problem step by step:\n\nProblem: {problem}\n\nSolution:"
    
  # 小学数学数据集（适合测试基础推理能力）
  gsm8k:
    name: "gsm8k"
    split: "test"
    max_samples: 500
    prompt_template: "Let's solve this step by step:\n\nQuestion: {question}\n\nAnswer:"
    
  # 数学选择题数据集
  mathqa:
    name: "math_qa"
    split: "test"
    max_samples: 500
    prompt_template: "Solve this math problem:\n\nProblem: {problem}\nOptions: {options}\n\nAnswer:"
    
  # 算术问题变体数据集
  svamp:
    name: "svamp"
    split: "test"
    max_samples: 200
    prompt_template: "Solve this arithmetic problem:\n\nProblem: {question}\n\nAnswer:"

# 难度等级映射
difficulty_mapping:
  elementary: ["grade_1", "grade_2", "grade_3", "grade_4", "grade_5", "grade_6"]
  middle: ["grade_7", "grade_8", "grade_9", "grade_10", "grade_11", "grade_12"]
  college: ["college"]

# 评估配置
evaluation:
  metrics: ["accuracy", "exact_match", "rouge", "bleu", "step_accuracy", "openai_score"]
  max_workers: 4
  batch_size: 8
  timeout: 300  # 每个问题的超时时间（秒）

# OpenAI评分配置
openai_scoring:
  enabled: false
  model: "gpt-3.5-turbo"
  temperature: 0.0
  max_tokens: 100
  prompt_template: |
    你是一个专业的数学教育评估专家。请对以下数学问题的回答进行评分。
    
    问题: {problem}
    标准答案: {reference_answer}
    学生回答: {student_answer}
    
    请从以下几个方面进行评分（总分100分）：
    1. 答案正确性（40分）：答案是否正确
    2. 解题思路（30分）：解题思路是否清晰合理
    3. 步骤完整性（20分）：解题步骤是否完整
    4. 表达清晰度（10分）：表达是否清晰易懂
    
    请只返回一个0-100之间的数字分数，不要其他内容。
  
# 输出配置
output:
  results_dir: "results"
  save_predictions: true
  save_metrics: true
  generate_plots: true
  save_model_outputs: true
  
# 系统配置
system:
  device: "auto"  # auto, cuda, cpu
  max_memory: "16GB"  # 最大内存使用
  seed: 42
  log_level: "INFO" 